### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane "starter kit" for your RFP with F-Droid. You can build on that, I'd suggest to eg move the screenshots inside this structure. For a guide, you can use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688).

### CODE REVIEW

**Comment by IzzySoft** [comment]
@saiga006 any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by saiga006** [comment]
Sorry I had totally missed this conversation, It will be done today

**Review by saiga006 — APPROVED** [review]
I will add the phone screenshots and app name to fastlane structure and create a tag based on that

**Comment by IzzySoft** [comment]
Thanks a lot! Small hint: a minor formatting error sneaked in with your update to `full_description.txt`: can you please insert an empty line before [line 4](https://github.com/saiga006/message-finder/blob/master/fastlane/metadata/android/en-US/full_description.txt#L4) to separate the "heading" (`<b>UseCase</b>`) from the paragraph? Else the two will "melt" into a single paragraph. For details, [here's a small reference](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) (see *Description › plain text* for what I call "Markdown Lite", which works as a very good compromise on F-Droid, my repo and Google Play).

Should your featureGraphic look strange, try the correct aspect ratio. Per definitionem, it should be either 1024x500 or 512x250 pixels. Also check how your icon will look at 48x48px (as used in app lists) – to me it would look better then without the text; but if you prefer it as-is, that's of course up to you :wink:

I've now enabled all aspects of fastlane you've set up in the metadata of my repo, so it will be pulled along with future releases when changed.

**Comment by IzzySoft** [comment]
PS, concerning the RFP: will you always create separate tags for Play Store and F-Droid, and keep the pattern `V<versionName>-fdroid_variant` for tag names? I'm asking because we need to include the tag name pattern with our metadata so our updater finds the correct tag – so once decided, you'd need to stick with them. If both use the same branch & commit, you could create a single tag covering them both. If they use different "build steps", so-called "build variants" could be used. Looking at the `build.gradle` my guess is that just a single tag (e.g. `v<versionName>`) would satisfy both – but again, it's your decision and we just need to know :wink:

**Comment by saiga006** [comment]
> I've now enabled all aspects of fastlane you've set up in the metadata of my repo, so it will be pulled along with future releases when changed.

So this particular change, will get reflect only from next app release right (based upon the tag), or else f-droid tracks the HEAD for description and screenshots ?
https://github.com/saiga006/message-finder/commit/adb1fe192ca2b8b16ee0cddde19b892ad057cdcb

> will you always create separate tags for Play Store and F-Droid, and keep the pattern V<versionName>-fdroid_variant for tag names

Since I'm currently using same codebase for amazon, f-droid and other app stores, I differentiate it now and then by tag names, so _its better to follow  V<versionName>-fdroid_variant._ 
For some stores, I would remove some part of the code and update only the binary here, so in that case I prefer not to mess up with only version based tag.

**Comment by IzzySoft** [comment]
> So this particular change, will get reflect only from next app release right (based upon the tag)

Yes, and another yes for "F-Droid & tag".

> or else f-droid tracks the HEAD for description and screenshots ?

No: F-Droid always focuses on the tag. The updater of my repo takes the APK from the tag – and when found, checks Fastlane at `HEAD`.

(tag names) Yes, understood – in this case it makes sense. But only if you release the specific versions at different "days" or really use a different code base. Most projects use gradle "build flavors" to differentiate the specific targets (like having FCM with the Google version, ADM with Amazon, and none of both with F-Droid). Then you only need one tag covering all of them, and F-Droid metadata in its build recipe just gets

```yaml
    gradle:
      - fdroid
```

to build the F-Droid specific variant and ignore the `gplay` and `amazon` variants.

> For some stores, I would remove some part of the code and update only the binary here

That would mean manual steps on each release. Build flavors would automate that. See e.g. [Gradle Build only a flavour](https://stackoverflow.com/q/21307444/2533433). Just a suggestion – the way you wrote is fine for F-Droid as well if you prefer the manual tasks.

**Comment by saiga006** [comment]
Thanks a lot for your suggestion, will consider the gradle based automation in next release. As of now, I prefer to manage it manual.

**Comment by IzzySoft** [comment]
Of course, all at your convenience! Always good to have options :smiley:

**Pull request merged**
